export const DEFAULT_AERODROMES = {
  SBPJ: {
    icao_code: 'SBPJ',
    name: 'Brigadeiro Lysias Rodrigues',
    city: 'Palmas',
    state: 'TO',
    arp_lat: -10.2914,
    arp_lon: -48.3569,
    elevation_ft: 774.0,
    magnetic_variation: -21.5,
  },
  SBBR: {
    icao_code: 'SBBR',
    name: 'Presidente Juscelino Kubitschek',
    city: 'Brasília',
    state: 'DF',
    arp_lat: -15.8711,
    arp_lon: -47.9186,
    elevation_ft: 3497.0,
    magnetic_variation: -22.0,
  },
  SBGR: {
    icao_code: 'SBGR',
    name: 'Guarulhos - Gov André Franco Montoro',
    city: 'Guarulhos',
    state: 'SP',
    arp_lat: -23.4356,
    arp_lon: -46.4731,
    elevation_ft: 2459.0,
    magnetic_variation: -22.5,
  },
  SBGL: {
    icao_code: 'SBGL',
    name: 'Galeão - Antonio Carlos Jobim',
    city: 'Rio de Janeiro',
    state: 'RJ',
    arp_lat: -22.81,
    arp_lon: -43.2506,
    elevation_ft: 28.0,
    magnetic_variation: -23.0,
  },
  SBEG: {
    icao_code: 'SBEG',
    name: 'Eduardo Gomes',
    city: 'Manaus',
    state: 'AM',
    arp_lat: -3.0386,
    arp_lon: -60.0497,
    elevation_ft: 264.0,
    magnetic_variation: -15.0,
  },
  SBRF: {
    icao_code: 'SBRF',
    name: 'Guararapes - Gilberto Freyre',
    city: 'Recife',
    state: 'PE',
    arp_lat: -8.1264,
    arp_lon: -34.9231,
    elevation_ft: 33.0,
    magnetic_variation: -22.0,
  },
  SBBE: {
    icao_code: 'SBBE',
    name: 'Val de Cans - Júlio Cezar Ribeiro',
    city: 'Belém',
    state: 'PA',
    arp_lat: -1.3792,
    arp_lon: -48.4764,
    elevation_ft: 54.0,
    magnetic_variation: -20.5,
  },
  SBCF: {
    icao_code: 'SBCF',
    name: 'Tancredo Neves',
    city: 'Confins',
    state: 'MG',
    arp_lat: -19.6244,
    arp_lon: -43.9719,
    elevation_ft: 2715.0,
    magnetic_variation: -22.5,
  },
  SBSV: {
    icao_code: 'SBSV',
    name: 'Deputado Luís Eduardo Magalhães',
    city: 'Salvador',
    state: 'BA',
    arp_lat: -12.9086,
    arp_lon: -38.3225,
    elevation_ft: 64.0,
    magnetic_variation: -22.5,
  },
  SBPA: {
    icao_code: 'SBPA',
    name: 'Salgado Filho',
    city: 'Porto Alegre',
    state: 'RS',
    arp_lat: -29.9944,
    arp_lon: -51.1714,
    elevation_ft: 11.0,
    magnetic_variation: -19.0,
  },
};
